version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
      - DB_NAME=${DB_NAME:-todo_db}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  postgres:
    environment:
      - POSTGRES_DB=${DB_NAME:-todo_db}
    ports:
      - "5433:5432"